### ISSUE TITLE
ARM64 host execution of crank agent builds x86_64 executable

### ISSUE THREAD

**Issue by RobertHenry6bev** [dotnet/crank#117]
I manually invoke the crank agent from source on an ARM64 host machine, following https://github.com/dotnet/crank/blob/master/docs/development.md

cd dotnet/crank/src/Microsoft.Crank.Agent
~/dotnet/dotnet run --hardware Physical --hardware-version "QEMU" --no-cleanup

This eventually fails.  It builds and then tries to run an x86_64 binary which does not work on ARM64 hardware.

11:03:47.117] Invoking executable: /tmp/benchmarks-agent/benchmarks-server-2913/4wticrvn.z0w/src/published/hello
[11:03:47.117]   Arguments:  
[11:03:47.117]   Working directory: /tmp/benchmarks-agent/benchmarks-server-2913/4wticrvn.z0w/src/published
[11:03:47.451] An unexpected error occurred while building the job. System.AggregateException: One or more errors occurred. (Exec format error)
 ---> System.ComponentModel.Win32Exception (8): Exec format error
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)

**Comment by RobertHenry6bev** [comment]
Reading the source code and experimenting, invoking with --hardware ARM64 seems to fix this issue

The documentation needs to be cleaned up.  Currently, the help info for --hardware prints:
    --hardware             Hardware (Cloud or Physical). Required.
And doesn't give the alternatives as taken from the enumeration in ./Microsoft.Crank.Models/Hardware.cs

**Comment by RobertHenry6bev** [comment]
Forging on, the crank agent downloads the wrong kind of binary for bombardier.

The URL is given in the ./Microsoft.Crank.Jobs.Bombardier/Program.cs source code:
                  bombardierUrl = "https://github.com/codesenberg/bombardier/releases/download/v1.2.4/bombardier-linux-amd64";
But this string assumes one is going to run bombardier on an amd64.  In my case I'm running on an ARM64.

**Comment by RobertHenry6bev** [comment]
I don't understand why the agent wants bombardier at all.  In my desired invocation, an agent runs the server (the unit under test/measurement/observation) and some other host machine is to run bombardier to bombard the server with incoming traffic.  Is there a way I can arrange this?

In any event, the github codesenberg bombardier doesn't even build a linux arm64 binary!
