### ISSUE TITLE
System.NullReferenceException in TraceEventDispatcher handler

### ISSUE THREAD

**Issue by tonyredondo** [dotnet/crank#265]
Hi, I'm having this exception when running crank over a simple ASP.NET core application written in net5.0 with a clr profiler attached.

```[05:18:23.644] Processing job 'application' (26) in state Starting
[05:18:23.956] Event pipe source created
[05:18:23.956] Processing event pipe source (application)...
[05:18:24.648] Processing job 'application' (26) in state Starting
[05:18:25.673] Processing job 'application' (26) in state Starting
[05:18:25.953] [ERROR] source.Process() -> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Crank.Agent.Startup.<>c__DisplayClass95_0.<StartCountersAsync>b__4(TraceEvent eventData) in /_/src/Microsoft.Crank.Agent/Startup.cs:line 4120
   at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.DoDispatch(TraceEvent anEvent)
   at Microsoft.Diagnostics.Tracing.EventPipeEventSource.DispatchEventRecord(EVENT_RECORD* eventRecord)
   at Microsoft.Diagnostics.Tracing.EventPipeEventSource.EventCache_OnEvent(EventPipeEventHeader& header)
   at Microsoft.Diagnostics.Tracing.EventPipe.EventCache.SortAndDispatch(Int64 stopTimestamp)
   at Microsoft.Diagnostics.Tracing.EventPipe.EventCache.ProcessEventBlock(Byte[] eventBlockData)
   at Microsoft.Diagnostics.Tracing.EventPipeBlock.FromStream(Deserializer deserializer)
   at FastSerialization.Deserializer.ReadObjectDefinition(Tags tag, StreamLabel objectLabel)
   at FastSerialization.Deserializer.ReadObject()
   at Microsoft.Diagnostics.Tracing.EventPipeEventSource.Process()
   at Microsoft.Crank.Agent.Startup.<>c__DisplayClass95_0.<StartCountersAsync>b__2() in /_/src/Microsoft.Crank.Agent/Startup.cs:line 4125
[05:18:25.956] Stopping event pipe session (application)...
[05:18:26.664] Processing job 'application' (26) in state Starting
[05:18:27.679] Processing job 'application' (26) in state Starting
[05:18:28.679] Processing job 'application' (26) in state Starting
[05:18:29.695] Processing job 'application' (26) in state Starting
[05:18:30.695] Processing job 'application' (26) in state Starting
[05:18:31.711] Processing job 'application' (26) in state Starting
[05:18:32.726] Processing job 'application' (26) in state Starting
[05:18:33.726] Processing job 'application' (26) in state Starting
[05:18:34.742] Processing job 'application' (26) in state Starting
[05:18:35.742] Processing job 'application' (26) in state Starting
[05:18:36.757] Processing job 'application' (26) in state Starting
[05:18:37.773] Processing job 'application' (26) in state Starting
[05:18:38.773] Processing job 'application' (26) in state Starting
[05:18:39.789] Processing job 'application' (26) in state Starting
[05:18:40.804] Processing job 'application' (26) in state Starting
[05:18:41.804] Processing job 'application' (26) in state Starting
[05:18:42.820] Processing job 'application' (26) in state Starting
[05:18:43.820] Processing job 'application' (26) in state Starting
[05:18:44.835] Processing job 'application' (26) in state Starting
[05:18:45.851] Processing job 'application' (26) in state Starting
[05:18:46.866] Processing job 'application' (26) in state Starting
[05:18:47.882] Processing job 'application' (26) in state Starting
[05:18:48.882] Processing job 'application' (26) in state Starting
[05:18:49.903] Processing job 'application' (26) in state Starting
[05:18:50.898] Processing job 'application' (26) in state Starting
[05:18:51.914] Processing job 'application' (26) in state Starting
[05:18:52.929] Processing job 'application' (26) in state Starting
[05:18:53.929] Processing job 'application' (26) in state Starting
[05:18:54.945] Processing job 'application' (26) in state Starting
[05:18:55.961] Processing job 'application' (26) in state Starting
[05:18:56.976] Processing job 'application' (26) in state Starting
[05:18:57.976] Processing job 'application' (26) in state Starting
[05:18:58.992] Processing job 'application' (26) in state Starting
[05:18:59.991] Processing job 'application' (26) in state Starting
[05:19:01.007] Processing job 'application' (26) in state Starting
[05:19:02.007] Processing job 'application' (26) in state Starting
[05:19:03.009] Processing job 'application' (26) in state Starting
[05:19:04.009] Processing job 'application' (26) in state Starting
[05:19:05.024] Processing job 'application' (26) in state Starting
[05:19:06.024] Processing job 'application' (26) in state Starting
[05:19:07.040] Processing job 'application' (26) in state Starting
[05:19:08.055] Processing job 'application' (26) in state Starting
[05:19:09.055] Processing job 'application' (26) in state Starting
[05:19:10.071] Processing job 'application' (26) in state Starting
[05:19:11.461] Processing job 'application' (26) in state Starting
[05:19:13.461] Processing job 'application' (26) in state Starting
[05:19:14.461] Processing job 'application' (26) in state Starting
[05:19:15.461] Processing job 'application' (26) in state Starting
[05:19:16.461] Processing job 'application' (26) in state Starting
[05:19:17.461] Processing job 'application' (26) in state Starting
[05:19:18.461] Processing job 'application' (26) in state Starting
[05:19:19.461] Processing job 'application' (26) in state Starting
[05:19:20.461] Processing job 'application' (26) in state Starting
[05:19:21.461] Processing job 'application' (26) in state Starting
[05:19:22.461] Processing job 'application' (26) in state Starting
[05:19:23.462] Processing job 'application' (26) in state Starting
[05:19:24.508] Processing job 'application' (26) in state Starting
[05:19:25.543] Processing job 'application' (26) in state Starting
[05:19:26.558] Processing job 'application' (26) in state Starting
[05:19:27.562] Processing job 'application' (26) in state Starting
[05:19:28.562] Processing job 'application' (26) in state Starting
[05:19:29.578] Processing job 'application' (26) in state Starting
[05:19:30.578] Processing job 'application' (26) in state Starting
[05:19:31.578] Processing job 'application' (26) in state Starting
[05:19:32.578] Processing job 'application' (26) in state Starting
[05:19:33.578] Processing job 'application' (26) in state Starting
[05:19:34.578] Processing job 'application' (26) in state Starting
[05:19:35.580] Processing job 'application' (26) in state Starting
[05:19:36.578] Processing job 'application' (26) in state Starting
[05:19:37.593] Processing job 'application' (26) in state Starting
[05:19:38.593] Processing job 'application' (26) in state Starting
[05:19:39.593] Processing job 'application' (26) in state Starting
[05:19:40.593] Processing job 'application' (26) in state Starting
[05:19:41.593] Processing job 'application' (26) in state Starting
[05:19:42.593] Processing job 'application' (26) in state Starting
[05:19:43.593] Processing job 'application' (26) in state Starting
[05:19:44.593] Processing job 'application' (26) in state Starting
[05:19:45.609] Processing job 'application' (26) in state Starting
[05:19:46.624] Processing job 'application' (26) in state Starting
[05:19:47.640] Processing job 'application' (26) in state Starting
[05:19:48.656] Processing job 'application' (26) in state Starting
[05:19:49.671] Processing job 'application' (26) in state Starting
[05:19:50.671] Processing job 'application' (26) in state Starting
[05:19:51.687] Processing job 'application' (26) in state Starting
[05:19:52.687] Processing job 'application' (26) in state Starting
[05:19:53.687] Processing job 'application' (26) in state Starting
[05:19:54.687] Processing job 'application' (26) in state Starting
[05:19:55.687] Processing job 'application' (26) in state Starting
[05:19:56.687] Processing job 'application' (26) in state Starting
[05:19:57.703] Processing job 'application' (26) in state Starting
[05:19:58.718] Processing job 'application' (26) in state Starting
[05:19:59.734] Processing job 'application' (26) in state Starting
[05:20:00.734] Processing job 'application' (26) in state Starting
[05:20:01.750] Processing job 'application' (26) in state Starting
[05:20:02.765] Processing job 'application' (26) in state Starting
[05:20:03.765] Processing job 'application' (26) in state Starting
[05:20:04.765] Processing job 'application' (26) in state Starting
[05:20:05.765] Processing job 'application' (26) in state Starting
[05:20:06.765] Processing job 'application' (26) in state Starting
[05:20:07.766] Processing job 'application' (26) in state Starting
[05:20:08.781] Processing job 'application' (26) in state Starting
[05:20:09.797] Processing job 'application' (26) in state Starting
[05:20:10.812] Processing job 'application' (26) in state Starting
[05:20:11.812] Processing job 'application' (26) in state Starting
[05:20:12.812] Processing job 'application' (26) in state Starting
[05:20:13.812] Processing job 'application' (26) in state Starting
[05:20:14.812] Processing job 'application' (26) in state Starting
[05:20:15.812] Processing job 'application' (26) in state Starting
[05:20:16.812] Processing job 'application' (26) in state Starting
[05:20:17.812] Processing job 'application' (26) in state Starting
[05:20:18.812] Processing job 'application' (26) in state Starting
[05:20:19.828] Processing job 'application' (26) in state Starting
[05:20:20.854] Processing job 'application' (26) in state Starting
[05:20:21.859] Processing job 'application' (26) in state Starting
[05:20:22.859] Processing job 'application' (26) in state Starting
[05:20:23.859] Processing job 'application' (26) in state Starting
[05:20:24.859] Processing job 'application' (26) in state Starting
[05:20:25.862] Processing job 'application' (26) in state Starting
[05:20:26.877] Processing job 'application' (26) in state Starting
[05:20:27.889] Processing job 'application' (26) in state Starting
[05:20:28.889] Processing job 'application' (26) in state Starting
[05:20:29.894] Processing job 'application' (26) in state Starting
[05:20:30.894] Processing job 'application' (26) in state Starting
[05:20:31.910] Processing job 'application' (26) in state Starting
[05:20:32.910] Processing job 'application' (26) in state Starting
[05:20:33.910] Processing job 'application' (26) in state Starting
[05:20:34.925] Processing job 'application' (26) in state Starting
[05:20:35.925] Processing job 'application' (26) in state Starting
[05:20:36.941] Processing job 'application' (26) in state Starting
[05:20:37.956] Processing job 'application' (26) in state Starting
[05:20:38.972] Processing job 'application' (26) in state Starting
[05:20:39.988] Processing job 'application' (26) in state Starting
[05:20:41.003] Processing job 'application' (26) in state Starting
[05:20:42.003] Processing job 'application' (26) in state Starting
[05:20:43.003] Processing job 'application' (26) in state Starting
[05:20:44.003] Processing job 'application' (26) in state Starting
[05:20:45.019] Processing job 'application' (26) in state Starting
[05:20:46.034] Processing job 'application' (26) in state Starting
[05:20:47.034] Processing job 'application' (26) in state Starting
[05:20:48.034] Processing job 'application' (26) in state Starting
[05:20:49.050] Processing job 'application' (26) in state Starting
[05:20:50.066] Processing job 'application' (26) in state Starting
[05:20:51.082] Processing job 'application' (26) in state Starting
[05:20:52.097] Processing job 'application' (26) in state Starting
[05:20:53.112] Processing job 'application' (26) in state Starting
[05:20:54.112] Processing job 'application' (26) in state Starting
[05:20:55.128] Processing job 'application' (26) in state Starting
[05:20:56.144] Processing job 'application' (26) in state Starting
[05:20:57.159] Processing job 'application' (26) in state Starting
[05:20:58.159] Processing job 'application' (26) in state Starting
[05:20:59.159] Processing job 'application' (26) in state Starting
[05:21:00.159] Processing job 'application' (26) in state Starting
[05:21:01.160] Processing job 'application' (26) in state Starting
[05:21:02.175] Processing job 'application' (26) in state Starting
[05:21:03.190] Processing job 'application' (26) in state Starting
[05:21:04.190] Processing job 'application' (26) in state Starting
[05:21:05.191] Processing job 'application' (26) in state Starting
[05:21:06.206] Processing job 'application' (26) in state Starting
[05:21:07.206] Processing job 'application' (26) in state Starting
[05:21:08.222] Processing job 'application' (26) in state Starting
[05:21:09.237] Processing job 'application' (26) in state Starting
[05:21:10.237] Processing job 'application' (26) in state Starting
[05:21:11.237] Processing job 'application' (26) in state Starting
[05:21:12.237] Processing job 'application' (26) in state Starting
[05:21:13.237] Processing job 'application' (26) in state Starting
[05:21:14.237] Processing job 'application' (26) in state Starting
[05:21:15.237] Processing job 'application' (26) in state Starting
[05:21:16.253] Processing job 'application' (26) in state Starting
[05:21:17.253] Processing job 'application' (26) in state Starting
[05:21:18.269] Processing job 'application' (26) in state Starting
[05:21:19.284] Processing job 'application' (26) in state Starting
[05:21:20.284] Processing job 'application' (26) in state Starting
[05:21:21.302] Processing job 'application' (26) in state Starting
[05:21:22.315] Processing job 'application' (26) in state Starting
[05:21:23.315] Processing job 'application' (26) in state Starting
[05:21:23.316] Job didn't start during the expected delay
[05:21:23.579] Driver stopping job '26'
[05:21:24.315] Processing job 'application' (26) in state Failed
[05:21:24.590] Driver deleting job '26'
[05:21:25.315] Processing job 'application' (26) in state Deleting
[05:21:25.316] Deleting job 'application' (26)
[05:21:25.316] Stopping heartbeat (application)... Success!
[05:21:25.316] Stopping counters event pipes for job 'application' (26)
[05:21:30.320] [ERROR] Counters could not be stopped in time for job 'application' (26)
[05:21:30.320] Counters stopped for job 'application' (26)
[05:21:30.321] /shutdown endpoint failed... '/shutdown'
[05:21:30.321] Forcing process to stop ...
[05:21:30.322] Waiting for process 2168 to stop ...
[05:21:31.336] Process has stopped
[05:21:31.336] Process stopped (Stopped)```

**Comment by sebastienros** [comment]
Can you give more details about the app and options so I can try to repro?

**Comment by sebastienros** [comment]
Haven't seen that in a while, assuming it has been fixed
