### ISSUE TITLE
PR bot assumes .NET is installed into a specific folder

### ISSUE THREAD

**Issue by martincostello** [dotnet/crank#394]
When using the `crank-pr` tool, the code assumes that a `.dotnet` folder exists containing `dotnet.exe`.

https://github.com/dotnet/crank/blob/70f76c0dd80674369fd2cd0a7a7ad522d7036c72/src/Microsoft.Crank.PullRequestBot/Program.cs#L597

If it does not, the process exits due to a `Win32Exception` being thrown because the attempt to invoke the process fails due to the file not existing.

```
[C:\Users\runneradmin\AppData\Local\Temp\crank-sandbox] .\.dotnet\dotnet.exe build-server shutdown
Unhandled exception: System.ComponentModel.Win32Exception (2): An error occurred trying to start process '.\.dotnet\dotnet.exe' with working directory 'C:\Users\runneradmin\AppData\Local\Temp\crank-sandbox'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Crank.PullRequestBot.ProcessUtil.RunAsync(String filename, String arguments, Nullable`1 timeout, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Boolean log, Action`1 onStart, Action`1 onStop, Boolean captureOutput, Boolean captureError, CancellationToken cancellationToken) in /_/src/Microsoft.Crank.PullRequestBot/ProcessUtil.cs:line 152
   at Microsoft.Crank.PullRequestBot.Program.RunBenchmark(Command command) in /_/src/Microsoft.Crank.PullRequestBot/Program.cs:line 597
   at Microsoft.Crank.PullRequestBot.Program.Controller(BotOptions options) in /_/src/Microsoft.Crank.PullRequestBot/Program.cs:line 213
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by sebastienros** [comment]
I changed to use "dotnet" but it means it has to be in the PATH. Did it work for you? It's only necessary that it works if the tool is run locally, but on a CI it can fail, it's just to be able to clean the repository.

**Comment by martincostello** [comment]
I've validated this now works with [this job](https://github.com/martincostello/crank-sandbox/runs/5077043404?check_suite_focus=true#step:6:214).
