### ISSUE TITLE
Unexpected error: failed to download PerfView.exe

### ISSUE THREAD

**Issue by ribubrar** [dotnet/crank#495]
Hi @sebastienros, I am stuck on this error. I appreciate any help you can provide. I can successfully run the benchmarks locally, but in CI/CD pipeline, on the agent pool, I get the error mentioned below. My question is, why does it need to download perfView? and how can I fix this error? Is there a way I can configure it not to download perfView unless necessary? 

I used a PowerShell script to initiate the agent and controller commands as background jobs.
```
$jobAgent = Start-Job -ScriptBlock {crank-agent} -Name jobAgent

$jobController = Start-Job -ScriptBlock {crank --config $(Build.SourcesDirectory)\benchmarks.yml --scenario Md5VsSha256 --profile local --sql "<ConnectionString>" --table CrankResult} -Name jobController

register-objectevent -inputobject $jobcontroller -eventname statechanged -action {
  $path = "C:\Crank\Log"
  If(!(test-path -PathType container $path))
  {
    New-Item -ItemType Directory -Path $path
  }

  $outputlocation = -join($path, "\", "output-021122-1534.txt")
  Get-job | Receive-Job -Keep 2>&1  >> $outputlocation

  get-content $outputlocation

  $artifactoryLocation = -join($(build.artifactorystagingdirectory), "\",  "output-021122-1534.txt")
  Write-host ("artifactoryLocation - $artifactoryLocation" )
  Get-job | Receive-Job -Keep 2>&1  >> $artifactoryLocation

  write-host ('job #{0} ({1}) complete.' -f $sender.id, $sender.name)
  get-job -name jobagent | stop-job    
  get-job -name jobagent | remove-job
  unregister-event $eventsubscriber.sourceidentifier
  remove-job $eventsubscriber.sourceidentifier
  remove-job -id $eventsubscriber.sourceobject.id
} | out-null

While (Get-Job -State "Running") {  
Get-Job
  Write-host ("Running... host" )
  Write-output ("Running... output" )
  write-output (Get-job | Receive-Job -Keep 2>&1)
  Start-Sleep 30        
}
```

Below is the stack trace of the error:
```
[07:52:29 INF] Created temp directory 'C:\Users\build.agent\AppData\Local\Temp\1\benchmarks-agent\benchmarks-server-7896\wjarlukl.ohx'
[07:52:29 INF] Agent ready, waiting for jobs...
[07:52:32 INF] Processing job 'application' (1) in state New
[07:52:32 INF] Acquiring Job 'application' (1)
[07:52:32 INF] Checking requirements...
[07:52:32 INF] Downloading PerfView to 'C:\Users\build.agent\AppData\Local\Temp\1\P2.0.68\PerfView.exe'
[07:52:32 INF] Downloading https://github.com/Microsoft/perfview/releases/download/P2.0.68/PerfView.exe
[07:52:33 ERR] Unexpected error
System.InvalidOperationException: Failed to download https://github.com/Microsoft/perfview/releases/download/P2.0.68/PerfView.exe after 5 attempts
   at Microsoft.Crank.Agent.Startup.DownloadFileAsync(String url, String outputPath, Int32 maxRetries, Int32 timeout, Boolean throwOnError) in /_/src/Microsoft.Crank.Agent/Startup.cs:line 4333
   at Microsoft.Crank.Agent.Startup.EnsureDotnetInstallExistsAsync() in /_/src/Microsoft.Crank.Agent/Startup.cs:line 5920
   at Microsoft.Crank.Agent.Startup.ProcessJobs(String hostname, String dockerHostname, CancellationToken cancellationToken) in /_/src/Microsoft.Crank.Agent/Startup.cs:line 605
[07:52:33 INF] Cancelling remaining jobs
[07:52:33 INF] Cleaning up temporary folder...
[07:52:33 INF] Deleting directory 'C:\Users\build.agent\AppData\Local\Temp\1\benchmarks-agent\benchmarks-server-7896'
[07:52:31.366] Running session '5c97d16e934c488fad575d5fdf3a7e09' with description ''
[07:52:31.481] Starting job 'application' ...
[07:52:31.877] Submitted job: http://localhost:5010/jobs/1
[07:52:48.035] ERROR while getting state on http://localhost:5010/jobs/1
Unhandled exception. System.Exception: Error while queuing job
    + CategoryInfo          : NotSpecified: (Unhandled excep...ile queuing job:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
    + PSComputerName        : localhost
 
   at Microsoft.Crank.Controller.JobConnection.StartAsync(String jobName) in 
/_/src/Microsoft.Crank.Controller/JobConnection.cs:line 117
   at Microsoft.Crank.Controller.Program.RunBenchmarkDotNet(Configuration configuration, String[] dependencies, String 
session) in /_/src/Microsoft.Crank.Controller/Program.cs:line 1318
   at Microsoft.Crank.Controller.Program.<>c__DisplayClass51_0.<<Main>b__1>d.MoveNext() in 
/_/src/Microsoft.Crank.Controller/Program.cs:line 628
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken 
cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.Crank.Controller.Program.Main(String[] args) in /_/src/Microsoft.Crank.Controller/Program.cs:line 0
```

**Comment by sebastienros** [comment]
Can you provide a PR that will make it not fail when perfview download fails, and display a warning? Worst case scenario the benchmarks won't be able to take a trace. The benchmark should not fail either.

**Comment by catcherwong** [comment]
I submitted a PR to fix this issue.
