### ISSUE TITLE
IndexOutOfRangeException when using crank compare on two microbenchmark results

### ISSUE THREAD

**Issue by westin-m** [dotnet/crank#623]
Running `crank compare benchmark-1.json benchmark-2.json` hits the following exception:
```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Crank.Controller.ResultComparer.<>c.<DisplayDiff>b__2_8(String[] segments) in /_/src/Microsoft.Crank.Controller/ResultComparer.cs:line 235
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.DistinctIterator`1.GetCount(Boolean onlyIfCheap)
   at Microsoft.Crank.Controller.ResultComparer.DisplayDiff(IEnumerable`1 allBenchmarks, IEnumerable`1 allNames) in /_/src/Microsoft.Crank.Controller/ResultComparer.cs:line 234
   at Microsoft.Crank.Controller.ResultComparer.Compare(IEnumerable`1 filenames, JobResults jobResults, Benchmark[] benchmarks, String jobName) in /_/src/Microsoft.Crank.Controller/ResultComparer.cs:line 64
   at Microsoft.Crank.Controller.Program.<>c__DisplayClass53_1.<Main>b__3() in /_/src/Microsoft.Crank.Controller/Program.cs:line 226
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass144_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.Crank.Controller.Program.Main(String[] args) in /_/src/Microsoft.Crank.Controller/Program.cs:line 692
```

This is currently reproducing on the latest version, 0.2.0-alpha.23414.1
[benchmark-1.json.txt](https://github.com/dotnet/crank/files/12384029/benchmark-1.json.txt)
[benchmark-2.json.txt](https://github.com/dotnet/crank/files/12384030/benchmark-2.json.txt)

**Comment by catcherwong** [comment]
This exception occurs when the compare benchmarks only have one benchmark, and the `FullName` are the same.

https://github.com/dotnet/crank/blob/6eee22ede372be35c9eb67d92686b4c50f6205da/src/Microsoft.Crank.Controller/ResultComparer.cs#L230-L249

`nameSegments.Values` will be empty after executing the loop.  Here should break the loop when the length of `nameSegments.Values` is 1, and it will use the last segment as the shortest name.

**Comment by catcherwong** [comment]
I submit a PR for this issue, and it can obtain the correct result based on the provided attachments.

![image](https://github.com/dotnet/crank/assets/8394988/a16b7a53-6df1-4667-aa06-c49a1a1774a4)
