### ISSUE TITLE
Agent crashed

### ISSUE THREAD

**Issue by kant2002** [dotnet/crank#89]
I run crank-agent from master.

I run crank job and by mistake press Enter instead of click on Allow. This trigger cancelling creation for firewall rule.
crank failed, but agent crashed as well too.

```
[08:10:49.313] {"spec":{"numberOfConnections":256,"testType":"timed","testDurationSeconds":15,"method":"GET","url":"http://localhost:5000/","body":"","stream":false,"timeoutSeconds":2,"client":"fasthttp"},"result":{"bytesRead":0,"bytesWritten":158720,"timeTakenSeconds":20.5850021,"req1xx":0,"req2xx":0,"req3xx":0,"req4xx":0,"req5xx":0,"others":512,"errors":[{"description":"the server closed connection before returning the first response byte. Make sure the server returns 'Connection: close' response header before closing the connection","count":512}],"latency":{"mean":1.006327409375e+07,"stddev":48776.50049402562,"max":1.0570021e+07,"percentiles":{"50":10047996,"75":10077999,"90":10107996,"95":10116000,"99":10566004}},"rps":{"mean":17.133376015997403,"stddev":203.08256544870855,"max":3473.336876838632,"percentiles":{"50":0.000000,"75":0.000000,"90":0.000000,"95":0.000000,"99":99.982503}}}}
Unhandled exception. System.InvalidOperationException: Process has exited, so the requested information is not available.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_WorkingSet64()
   at Microsoft.Crank.Agent.Startup.<>c__DisplayClass60_5.<ProcessJobs>b__16(Object _) in c:\GitHub\dotnet\crank\src\Microsoft.Crank.Agent\Startup.cs:line 870
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
```

**Comment by sebastienros** [comment]
It has been fixed recently. https://github.com/dotnet/crank/commit/0699c865749dda30d353d110ae76ee13aa22c234
