### ISSUE TITLE
Cannot relaunch after failure

### ISSUE THREAD

**Issue by kant2002** [dotnet/crank#90]
After I experience #89 the hello task does not work anymore. I complains about address in use. "Failed to bind to address http://[::]:5000: address already in use."

Not sure that this is crank issue, or hello example.

```
crank --config samples/hello/hello.benchmarks.yml --scenario hello --profile local --application.options.displayOutput true
[08:24:59.452] Running session '314abc03af4a432f88872e712807d495' with description ''
[08:24:59.516] Starting job 'application' ...
[08:24:59.567] Fetching job: http://localhost:5010/jobs/3
[08:25:00.593] Job has been selected by the server ...
[08:25:00.596] Job is now building ...
[application] AspNetCore location: C:\Users\kant\AppData\Local\Temp\benchmarks-agent\benchmarks-server-3504\bxtapxpz.wjm\crank\samples\hello\published\Microsoft.AspNetCore.Hosting.Abstractions.dll
[application] AspNetCore version: 3.1.6
[application] NETCoreApp location: C:\Users\kant\AppData\Local\Temp\benchmarks-agent\benchmarks-server-3504\bxtapxpz.wjm\crank\samples\hello\published\System.Private.CoreLib.dll
[application] NETCoreApp version: 3.1.5-servicing.20269.1+018cfd06dceb19b6eb1e9217a500fb1071946fcd
[application] crit: Microsoft.AspNetCore.Server.Kestrel[0]
[application]       Unable to start Kestrel.
[application] System.IO.IOException: Failed to bind to address http://[::]:5000: address already in use.
[application]  ---> Microsoft.AspNetCore.Connections.AddressInUseException: Only one usage of each socket address (protocol/network address/port) is normally permitted.
[application]  ---> System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted.
[application]    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
[application]    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
[application]    at System.Net.Sockets.Socket.Bind(EndPoint localEP)
[application]    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
[application]    --- End of inner exception stack trace ---
[application]    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
[application]    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
[application]    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
[application] --- End of stack trace from previous location where exception was thrown ---
[application]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
[application]    --- End of inner exception stack trace ---
[application]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
[application]    at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
[application]    at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
[application]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
[application]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
[application]    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
[application] [STDERR] Unhandled exception. System.IO.IOException: Failed to bind to address http://[::]:5000: address already in use.
[application] [STDERR]  ---> Microsoft.AspNetCore.Connections.AddressInUseException: Only one usage of each socket address (protocol/network address/port) is normally permitted.
[application] [STDERR]  ---> System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted.
[application] [STDERR]    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
[application] [STDERR]    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
[application] [STDERR]    at System.Net.Sockets.Socket.Bind(EndPoint localEP)
[application] [STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
[application] [STDERR]    --- End of inner exception stack trace ---
[application] [STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
[application] [STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
[application] [STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
[application] [STDERR] --- End of stack trace from previous location where exception was thrown ---
[application] [STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
[application] [STDERR]    --- End of inner exception stack trace ---
[application] [STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
[application] [STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
[application] [STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
[application] [STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
[application] [STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
[application] [STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
[application] [STDERR]    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
[application] [STDERR]    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
[application] [STDERR]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
[application] [STDERR]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
[application] [STDERR]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
[application] [STDERR]    at hello.Program.Main(String[] args) in C:\Users\kant\AppData\Local\Temp\benchmarks-agent\benchmarks-server-3504\bxtapxpz.wjm\crank\samples\hello\Program.cs:line 21
[08:25:21.858] Job failed on benchmark server, stopping...

[08:25:21.861] Job has failed, interrupting benchmarks ...
[08:25:21.870] Stopping job 'application' ...
[08:25:23.185] Deleting job 'application' ...

application
-------

## Host Process:
CPU Usage (%):        2
Raw CPU Usage (%):    16.90
Working Set (MB):     34
Build Time (ms):      9,150
Published Size (KB):  86,819
```

**Comment by sebastienros** [comment]
I fix the related issue.

You might need to kill some processes that are still running and holding on the 5000 ports. Try to kill all "dotnet" tasks.
